### ISSUE TITLE
ArtNetServer blocks when used as sender

### ISSUE THREAD

**Issue by schw4rzlicht** [cansik/artnet4j#5] opened 2018-04-05 03:17 UTC
When using artnet4j only to send broastcast packets using `ArtNetClient` (as shown in the [readme](../blob/master/README.md)), it is not possible to stop the Client using `ArtNetClient.stop()` since the underlying `ArtNetServer` thread uses `DatagramSocket.receive()`, which according to the Javadocs blocks until a datagram is received.

Wouldn't it be a good idea to make sending possible without the need to listen at the same time? Then there wouldn't be a thread do deal with in the first place.

*EDIT:* Another approach would be to close the socket in `ArtNetServer.stop()`. `DatagramSocket.receive()` would then throw an `IOException` according to the docs which could be ignored if a corresponding flag is set in `ArtNetServer`.

**Comment by cansik** [comment] 2018-04-05 11:57
To the first question about the start and stopping, that is totally true. The problem is that the underlaying framework is still the "old" artnet4j code and needs a lot of refactoring. Yes the approach with closing the socket is a good idea and I will implement it in the next version (already fixed it now).

The second question is something that bothers me too. But for this I think I have to fully refactor the underlaying `ArtNetServer` class which is handling the networking. It is currently server and client which is not really useful. It would be better to create an `ArtNetServer` for receiving data and an `ArtNetClient` for sending data.

Currently the `ArtNetClient` is more a decorator / wrapper for the `ArtNetServer` which makes the API simpler. This would then be useful for both, the new `ArtNetServer` and `ArtNetClient`.

Because a lot of people are used to the old artnet4j API, I just added some fixes, but did not a complete refactoring of the framework. Maybe it would make sense to do so.

**Comment by cansik** [comment] 2018-04-05 11:59
It would be nice if you could test, if the `stop` method now works as expected.

Here is the new compiled binary if you need it:
[artnet4j.zip](https://github.com/cansik/artnet4j/files/1879894/artnet4j.zip)

**Comment by schw4rzlicht** [comment] 2018-04-05 12:44
That did the trick.

Regarding the refactor: I might do this (at least for the sender part) because the current API unnecessarily bloats my project with a new thread. If I do it in the near future, I'd fork and create a pull request.

**Closed as completed** 2018-06-25 10:36 UTC
Labels: bug
